### ISSUE TITLE
Install Problem On Linux

### ISSUE THREAD

**Issue by yang-zhongtian** [lodevil/Lo-runner#18]
``` 
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lorun
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/Lo-runner/lorun/__init__.py", line 1, in <module>
    from ._lorun_ext import run, check
ImportError: No module named 'lorun._lorun_ext'
```

**Comment by Jed-Z** [comment]
Did you install the package on your system? Use `sudo python3 setup.py install`.
